site_name: FAIR Jupyter
site_url: https://fusion-jena.github.io/fairjupyter
repo_url: https://github.com/fusion-jena/fairjupyter
docs_dir: content
nav:
  - Home: index.md
theme:
  name: material
extra_css:
  - stylesheets/fairjupyter.css
