# Article by keywords, e.g., `open source'
SELECT DISTINCT ?article ?keywords WHERE {
  ?article <https://w3id.org/reproduceme/keywords> ?keywords .
  FILTER (REGEX(LCASE(?keywords), "open(.)source"))
}
