# Match articles between FAIR Jupyter and Wikidata via DOI

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wikidata_wd: <http://www.wikidata.org/entity/>
PREFIX wikidata_wdt: <http://www.wikidata.org/prop/direct/>

SELECT DISTINCT

 ?fj_article
 ?wikidata
 ?wikidata_label
 ?DOI

WHERE {
  ?fj_article <https://w3id.org/reproduceme/doi> ?doi .
  BIND(UCASE(?doi) AS ?DOI)
  service <https://query.wikidata.org/sparql> {
    ?wikidata wikidata_wdt:P356 ?DOI .
    ?wikidata rdfs:label ?wikidata_label .
    FILTER (LANG(?wikidata_label) = "en")
  }
}
LIMIT 100