PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

PREFIX wikidata_wd: <http://www.wikidata.org/entity/>
PREFIX wikidata_wdt: <http://www.wikidata.org/prop/direct/>

SELECT DISTINCT

 ?fj_article
 ?wikidata
 ?wikidata_label
 ?DOI

WHERE {
  ?fj_article <http://www.w3.org/ns/prov-o#specializationOf> ?mesh_url .
  BIND(REPLACE(STR(?mesh_url), ".*MESH/D", "D") AS ?MESH)
  service <https://query.wikidata.org/sparql> {
    ?wikidata wikidata_wdt:P486 ?MESH .
    ?wikidata rdfs:label ?wikidata_label .
    FILTER (LANG(?wikidata_label) = "ml")
  }
}
LIMIT 100