SELECT ?language (COUNT(?notebook) as ?notebook_count)
WHERE {
  ?notebook a <https://w3id.org/reproduceme/Notebook> ;
            <https://w3id.org/reproduceme/language> ?language .
}
GROUP BY ?language
ORDER BY DESC(?notebook_count)
LIMIT 10